os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.2

# install:
# #  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
#   - sudo apt-get install python-pip
#   - sudo pip install python-swiftclient

# script:
#   - swift build
#   - swift build -c release

script:
  - eval "$(curl -sL https://swift.vapor.sh/ci)"
  - eval "$(curl -sL https://swift.vapor.sh/codecov)"

notifications:
  email: false
